### ISSUE TITLE
Crashes as soon as launched

### ISSUE THREAD

**Issue by agektmr** [maxlgu/BobBucksAndroidPaymentApp#1]
The app crashes as soon as it's launched.
This may be because I'm using old-ish build of Android 12 on Pixel 3 but can you check?

**Comment by liquangumax** [comment]
It crashes on my side as well. I've just fixed the crash. It was caused by a mismatch in activity name. Nothing needs to be changed on bobbucks.dev.

Thanks for your report!

**Comment by maxlgu** [comment]
Fixed by https://github.com/maxlgu/BobBucksAndroidPaymentApp/commit/817fb1980c297e8e996849d72df7814d02d5a45b
